### PR TITLE
Check if scheme can be opened before opening

### PR DESCRIPTION
**Pull request by boyvanamstel**
This commit adds a check to the helper that will retrieve the path to the app that responds to the given scheme. Failure to retrieve this path means the app does not exist on the system and the scheme shouldn't be called.

It's a fix for a relatively rare case when the container app has been moved to the Trash, but the helper is still in launchd. The OS will throw errors stating the scheme can't be opened.

### CODE REVIEW

**Comment by boyvanamstel** [comment]
Why not just merge in the commit..?

**Comment by JanX2** [comment]
I didn’t merge this, because my branch is ahead of this repo and there would have been conflicts.

**Comment by boyvanamstel** [comment]
Is it really too much trouble to solve a simple merge conflict?? Now there will definitely be a conflict when kgn decides to merge my pull request before yours..

**Comment by JanX2** [comment]
I’m sorry @boyvanamstel, but I am not the maintainer (@kgn). I credited you, if that’s any consolation to you! This just seemed the cleaner approach.

**Comment by boyvanamstel** [comment]
I know you're not the maintainer and I don't care about the credits (they are appreciated though), I just don't get why you chose to copy-paste code instead of using git to merge this properly into your code. This definitely makes it more complicated for @kgn to merge both pull requests.

Anyway, let's get this back on topic ;).

**Pull request merged**
