### PR TITLE
Bindings support

### PR DESCRIPTION
**Pull request by jwilling**
Sorry for the delay on this one. I had forgotten to submit a pull request. ;)

As per the commit notes:

> Interface Builder support can be achieved by adding a generic NSObject
> in IB, then by changing the class to `LLManager`. Then the
> `launchAtLogin` property can be bound.

### CODE REVIEW

**Comment by kgn** [comment]
Great! Would you mind adding the IB info to the readme please, at the bottom of how to.

**Comment by jwilling** [comment]
Okay, I added a note. Let me know if I need to clarify anything.

**Comment by jwilling** [comment]
Hold on, don't merge this. Something got a little wonky with conflicts.

**Comment by jwilling** [comment]
Bah, I'll just recreate my fork and start over.

**Pull request closed without merging**
